apiVersion: v1
kind: Pod
metadata:
  name: my-second-pod
spec:
  containers:
  - name: my-container
    image: docker.io/alpine:latest  # Example of a different image
    command: ["sleep", "3600"]       # Example command to keep the container running
